### PR TITLE
Please accept my pull request

### PR DESCRIPTION
**Pull request by DaveBabler**
Note: I slightly modified some of the SQL calls in the index.html page.  They are more objectified instead of procedural. 
Please review my work at this link _**prior**_ to accepting my pull request.
http://dbabler.yaacotu.com/FED_2019/
(proceed directly to the inventory section).

If you need a upc to test for insert here is one to copy and paste for your convenience `787692835140`

Thank you!
Dave Babler

### CODE REVIEW

**Comment by tmajchrz** [comment]
This is great, Dave!  

I like how it lets me know if the UPC has been added to the database, or if it already exists in the database, that the quantity has been updated.

Can you change "Colloquially known as:" to "Description," so it matches the inventory columns displayed on the page below it.  Also, rather than a number for Product Type, can you please display the corresponding text (e.g. Alternative Food, Toiletries, etc.) instead.

**Comment by DaveBabler** [comment]
I’ll be in shortly to talk to you about this. I think either w3 does not explain Ajax well or I’m too stupid to grasp it. I just parked and am heading to the building

**Comment by DaveBabler** [comment]
Dr. M, 
I have made the requested changes.  You can verify this by going to 
http://dbabler.yaacotu.com/FED_2019/

**Comment by DaveBabler** [comment]
Oh and...yes this means I solved my AJAX problem.  I can explain it if you like next "scrum"

**Comment by DaveBabler** [comment]
Please verify my changes.
I have added the search by UPC to the master as well.  though I will create a separate pull request for that specific branch (assuming git hub lets me).

**Comment by DaveBabler** [comment]
As always you may view my work here: 
http://dbabler.yaacotu.com/FED_2019/index.php#

**Comment by tmajchrz** [comment]
Dave,

Please send a pull request for the current version of your code.  I'll try to pull the latest version, which appears to be functioning properly at the URLs below.

http://dbabler.yaacotu.com/FED_2019/inventoryCheckout.php#
http://dbabler.yaacotu.com/FED_2019/inventoryMain.php#

Thanks!
Dr. M

**Pull request closed without merging**
